### ISSUE TITLE
Homework 2 TODO

### ISSUE THREAD

**Issue by imAlessas** [imAlessas/computer-networks#9]
- [x] Write detailed introduction
- [x] Rewrite project parameters 
- [x] Finish throughout section by inserting formulas and explanation 
- [x] Write the conclusion
